// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhcpljdgookohaoeqpcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRoY3BsamRnb29rb2hhb2VxcGN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMDI2ODIsImV4cCI6MjA2NDc3ODY4Mn0.whX0yCJlpHU_2JE115mX2PZvLuzbzAxCYc79hGiCo5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);